name: Build

on:
    push:
        branches:
            - 'main'
        tags:
            - 'v[0-9]+.[0-9]+.[0-9]+'
            - 'v[0-9]+.[0-9]+.[0-9]+-**'
        paths-ignore:
            - '**.md'
            - '**.spec.js'
            - '.idea'
            - '.vscode'
            - '.dockerignore'
            - 'Dockerfile'
            - '.gitignore'

jobs:
    build:
        runs-on: ${{ matrix.os }}

        permissions:
            contents: write

        strategy:
            matrix:
                os:
                    # - macos-latest
                    - windows-latest
                    # - ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Set Mac API key
              if: startsWith(matrix.os, 'macos')
              run: |
                  mkdir -p ~/private_keys/
                  echo '${{ secrets.APPLE_API_KEY_CONTENT }}' > ~/private_keys/AuthKey_${{ secrets.APPLE_API_KEY_ID }}.p8

            - uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest
            
            - name: Install dependencies
              run: bun install --frozen-lockfile

            - name: Set environment variables
              shell: bash
              run: |
                  echo "VITE_SUPABASE_API_URL=${{ secrets.SUPABASE_API_URL }}" >> $GITHUB_ENV
                  echo "VITE_SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}" >> $GITHUB_ENV
                  echo "VITE_MIXPANEL_TOKEN=${{ secrets.MIXPANEL_TOKEN }}" >> $GITHUB_ENV
                  echo "VITE_ANTHROPIC_API_KEY=${{ secrets.ANTHROPIC_API_KEY }}" >> $GITHUB_ENV
                  echo "VITE_OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV
                  echo "VITE_LANGFUSE_PUBLIC_KEY=${{ secrets.LANGFUSE_PUBLIC_KEY }}" >> $GITHUB_ENV
                  echo "VITE_LANGFUSE_SECRET_KEY=${{ secrets.LANGFUSE_SECRET_KEY }}" >> $GITHUB_ENV

            - name: Build foundation
              run: |
                  bun build:foundation
                  bun run build
            
            - name: Build/Release Mac app
              if: startsWith(matrix.os, 'macos')
              uses: samuelmeuli/action-electron-builder@v1
              with:
                  skip_build: true
                  package_root: apps/studio
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  release: ${{ startsWith(github.ref, 'refs/tags/v') }}
                  mac_certs: ${{ secrets.MAC_CERTS }}
                  mac_certs_password: ${{ secrets.MAC_CERTS_PASSWORD }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  APPLE_API_KEY: ${{ startsWith(matrix.os, 'macos') && format('~/private_keys/AuthKey_{0}.p8', secrets.APPLE_API_KEY_ID) || '' }}
                  APPLE_API_KEY_ID: ${{ secrets.APPLE_API_KEY_ID }}
                  APPLE_API_ISSUER: ${{ secrets.APPLE_API_ISSUER }}

            - name: Set Windows environment variables
              if: startsWith(matrix.os, 'windows')
              shell: bash
              run: |
                  # Set version from package.json
                  APP_VERSION=$(node -p "require('./apps/studio/package.json').version")
                  echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV

            - name: Package Windows app
              if: startsWith(matrix.os, 'windows')
              working-directory: apps/studio
              run: yarn && yarn run electron-builder --win --dir
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            
            - name: Sign Windows app
              if: startsWith(matrix.os, 'windows')
              uses: azure/trusted-signing-action@v0.3.16
              with:
                  azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                  azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
                  azure-client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
                  endpoint: ${{ secrets.AZURE_ENDPOINT }}
                  code-signing-account-name: ${{ secrets.AZURE_CODE_SIGNING_NAME }}
                  certificate-profile-name: ${{ secrets.AZURE_CERT_PROFILE_NAME }}
                  file-digest: SHA256
                  files-folder: apps/studio/release/${{ env.APP_VERSION }}/win-unpacked
                  files-folder-filter: exe
                  timestamp-rfc3161: http://timestamp.digicert.com

            - name: Verify Windows app signatures
              if: startsWith(matrix.os, 'windows')
              shell: powershell
              run: |
                $files = Get-ChildItem -Path "apps/studio/release/${{ env.APP_VERSION }}/win-unpacked/*.exe" -Recurse
                foreach ($file in $files) {
                    Write-Host "Verifying signature for: $($file.FullName)"
                    $sig = Get-AuthenticodeSignature $file.FullName
                    if ($sig.Status -ne "Valid") {
                        Write-Host "Invalid signature found for $($file.FullName)"
                        Write-Host "Status: $($sig.Status)"
                        Write-Host "Signer: $($sig.SignerCertificate.Subject)"
                        exit 1
                    }
                    Write-Host "Valid signature found:"
                    Write-Host "Status: $($sig.Status)"
                    Write-Host "Signer: $($sig.SignerCertificate.Subject)"
                    Write-Host "Timestamp: $($sig.TimeStamper)"
                }
            - name: Upload Windows Artifacts
              if: startsWith(matrix.os, 'windows')
              uses: actions/upload-artifact@v4
              with:
                name: signed-windows-binaries
                path: apps/studio/release/${{ env.APP_VERSION }}/win-unpacked/*.exe

            - name: Publish Windows app
              working-directory: apps/studio
              if: startsWith(matrix.os, 'windows') && startsWith(github.ref, 'refs/tags/v')
              run: yarn run electron-builder --win --publish always --prepackaged release/${{ env.APP_VERSION }}/win-unpacked
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}